# Generated by Django 3.2.21 on 2023-10-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('K Club', 'The K Club'), ('Ballybunnion', 'Ballybunnion'), ('The Abbey', 'The Abbey')], default='The K Club', max_length=20),
        ),
    ]
