# Generated by Django 3.2.24 on 2024-02-28 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0002_auto_20240226_2304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='golfcourse',
            name='image',
        ),
        migrations.RemoveField(
            model_name='golfcourse',
            name='name',
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='course_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='golfcourse',
            name='user',
            field=models.ForeignKey(max_length=10, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
