# Generated by Django 3.2.24 on 2024-02-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20240228_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='created_on',
            field=models.DateTimeField(),
        ),
    ]
