# Generated by Django 3.2.24 on 2024-02-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_delete_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='golfcourse',
            name='created_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
