# Generated by Django 4.2.10 on 2024-03-05 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_content_addgolfcourse_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addgolfcourse',
            old_name='description',
            new_name='content',
        ),
    ]
