# Generated by Django 3.2.24 on 2024-02-29 22:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0006_alter_golfcourse_created_on'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GolfCourse',
            new_name='AddGolfCourse',
        ),
    ]
